version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    restart: always
    network_mode: "host"
  explorer:
    image: fuocnetwork/blockscout
    container_name: explorer
    network_mode: "host"
    environment:
      - NETWORK=FUOC
      - SUBNETWORK=FUOC
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=rpc
      - ETHEREUM_JSONRPC_WS_URL=rpc
      - COIN=FUOC
      - DISABLE_EXCHANGE_RATES=true
      - SHOW_PRICE_CHART=false
      - SHOW_TXS_CHART=true
      - DATABASE_URL=postgresql://postgres:secret@postgres:5432/blockscout?ssl=false
    depends_on:
      - postgres
